version: "3.8"
services:
  # Database application service
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventdb
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend application service
  event:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8087:8087
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/eventdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  mysql_data: